version: '2'

volumes:
  elasticsearch_data: {}
  postgres_data: {}
  nginx_tls: {}

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=tinyauth
    - POSTGRES_USER=tinyauth
    - POSTGRES_PASSWORD=tinyauth

  tinyauth:
    image: tinyauth/tinyauth:dev
    environment:
    - POSTGRES_USER=tinyauth
    - POSTGRES_PASSWORD=tinyauth
    ports:
    - "127.0.0.1:5000:5000"

  elasticsearch:
    build: .
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    build:
      context: kibana
      dockerfile: Dockerfile
    depends_on:
    - elasticsearch

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
    - kibana
    volumes:
      - nginx_tls:/etc/nginx/external/
    ports:
      - "127.0.0.1:443:443"
